<a href="https://colab.research.google.com/github/Gurpreetkaur977/Gurpreet/blob/main/Copy_of_gurpreet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Assignment **1**

## 1.Create variables to store your name (string), age (integer), and course (string). Print all of them using a single print() statement.

In [ ]:
name="gurpreet kaur"
age=19
course="b.Tech"
print(name,age,course)


gurpreet kaur 19 b.Tech


###  2.Write a program to swap two numbers without using a third variable. Example: a = 4, b = 9.

In [ ]:
a=4
b=9
a,b=b,a
print(a,b)

9 4


### 3.Take two numbers from the user and display:
• Sum
• Difference
• Product
• Quotient
• Remainder

In [ ]:
a=12
b=4
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)




16
8
48
3.0
0


#### 4.Take marks of 5 subjects and calculate the total and percentage


In [ ]:
english=80
punjabi=80
maths=79
science=79
hindi=80
total=english+punjabi+maths+science+hindi
print(total/400*100)

99.5


### 5.Start with x = 10. Then:
• Add 5 using +=
• Multiply by 2 using *=
• Subtract 4 using -=
• Divide by 2 using /=
Print the value after each operation.

In [ ]:
x=10
x+=2
print(x)
x=10
x*=2
print(x)
x=10
x-=4
print(x)
x=10
x/=2
print(x)





12
20
6
5.0


### 6.Write a program that compares two numbers and prints:
• Whether they are equal
• Whether the first is greater
• Whether the second is greater

In [ ]:
a=24
b=18
print(a==b)
print(a>b)
print(a<b)

False
True
False


#### 7.Write a program that compares two numbers and prints:
• Whether they are equal
• Whether the first is greater
• Whether the second is greater



In [ ]:
is_raining= True
have_umbrella=False
print(is_raining and have_umbrella)
print(is_raining or have_umbrella)



False
True


### 8.Create two identical lists and compare them using:
• ==
• is
Print and explain the result.

In [ ]:
l1=[12,45,56,34,15]
l2=[12,45,56,34,15]
print(l1==l2)
print(l1 is l2)

True
False


### 9.Take two numbers and show the result of:
• Bitwise AND (&)
• Bitwise OR (|)
• Bitwise XOR (^)

In [ ]:
n1=1011
n2=1110
print(n1 & n2)
print(n1 | n2)
print(n1 ^ n2)

82
2039
1957


#### 10.Take user input for an integer and a float. Add them and print:
• Their types using type()
• Their sum as an integer


In [ ]:
a=5
n=float(a)
print(n)
print(type(n))

5.0
<class 'float'>


##Assignment 2

## 1. WAP to print number 1 to 10 but stop the loop when number reach 9

In [ ]:
count=0
while (count<10):
  print(count)
  count=count+1


0
1
2
3
4
5
6
7
8
9


## 2.WAP that keep asking the user to enter the number and stop when the user enter a negative number

In [ ]:
while True:
  r=int(input("enter the number="))
  if (r>0):
    print("number is positive")
  else:
    print("number is negative")
    break

enter the number=01
number is positive
enter the number=-6
number is negative


### 3.WAP to find first even number in a list using a for loop and break.

In [ ]:
L=[1,3,5,6,3,78,89,88,78,76,99,55,33]
for i in range (len(L)):
  if (L[i]%2==0):
    print("first even number is ",L[i])
    break


first even number is  6


## 4. keep adding number onwords until total sum exceeds 25 print last sum and digit

In [ ]:
sum=0
for i in range(0,50):
  sum+=i
  if sum<25:
    print("last sum=",sum)
    print("last digit =",i)

last sum= 0
last digit = 0
last sum= 1
last digit = 1
last sum= 3
last digit = 2
last sum= 6
last digit = 3
last sum= 10
last digit = 4
last sum= 15
last digit = 5
last sum= 21
last digit = 6


## 5.keep asking the user to guess the password until they guess admin123 . use while and break

In [ ]:
while True:
  x=input("enter the password:")
  if (x=="admin123"):
    print("correct pass")
    break
  else:
    print("wrong pass")


enter the password:123
wrong pass
enter the password:admin123
correct pass


## 6. Print the multiples of 7 using while loop stop if value is greater than 100


In [ ]:
count=0
while (count<100):
  print(count)
  count+=7

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


## 7. Give a number, print each digit until zero is found

In [ ]:
y=input("enter the number=")
for i in y:
    if i=="0":
      print("zero is found")
      break
    print(i)

enter the number=07
zero is found


In [ ]:
for i in range(1,20):
  n=input("enter the value =")
  if n=="0":
    print("zero is found")
    break
  print(i)
3

1
2


#### **Assignment 3**

### 1. Take a sentence and reverse the order of its words. Example: "I love Python" → "Python love I"

In [ ]:
sentence="i love python"
words=sentence.split()
words.reverse()
reversed_sentence=' '.join(words)
print(reversed_sentence)

### 2. Given a string, count consonants (non-vowel letters, ignoring case). Example: "Hello World" →
7 (H, l, l, W, r, l, d).

In [ ]:
x=input("enter a string: ")
vowels='aeiouAEIOU'
consonants=[i for i in x if i.isalpha() and i not in vowels]
count=len(consonants)
print(f"{count}({','.join(consonants)})")


### 3.Check if two strings are anagrams (same characters, same frequency, ignoring case).
Example: "Listen", "Silent" → "Anagram", "Hello", "World" → "Not Anagram".

In [ ]:
s1="listen"
s2="silent"
s1_sorted=sorted(s1.lower())
s2_sorted=sorted(s2.lower())
if s1_sorted==s2_sorted:
  print("anagram")
else:
  print("not anagram")




anagram


### 4. Find the first character in a string that appears only once (case-sensitive). Example: "swiss" →
"w", "programming" → "r".


In [ ]:
string="swiss"
for ch in string:
  if string.count(ch)==1:
    print(ch)
    break

w


### 5.Compress a string by replacing repeated characters with the character and count. Example:
"aaabbc" → "a3b2c1". If compressed string isn’t shorter, return original.

In [ ]:
s="aaabbc"
compressed=""
i=0
while i<len(s):
  count=1
  while i+1<len(s) and s[i]==s[i+1]:
    count+=1
    i+=1
  compressed+=s[i]+str(count)
  i+=1
if len(compressed)<len(s):
    print(compressed)
else:
    print(s)

aaabbc


### 6.Find the longest substring in a string that is a palindrome (case-sensitive). Example: "babad" →
"bab" (or "aba"), "cbbd" → "bb". If multiple exist, return the first.

In [ ]:
s="babab"
max_len=0
result=""
for i in range(len(s)):
  for j in range(i+1,len(s)+1):
    substr=s[i:j]
    if substr==substr[::-1] and len(substr)>max_len:
      result=substr
      max_len=len(substr)
      print(result)

b
bab
babab


### 7.Given a string containing only '(', ')', '{', '}', '[', ']', check if the sequence is valid (properly nested
and closed). Example: "({[]})" → "Valid", "(]" → "Invalid".


In [ ]:
s="({[]})"
stack=[]
mapping={')':'(','}':'{',']':'['}
valid=True
for ch in s:
  if ch in mapping.values():
    stack.append(ch)
  elif ch in mapping:
    if not stack or stack.pop()!=mapping[ch]:
      valid=False
      break
if stack:
    valid=False
print("valid" if valid else"invalid")


valid


### 8. Given a start word, end word, and a list of valid words, find the minimum number of steps to
transform the start word to the end word by changing one letter at a time, where each
intermediate word must be in the list. All words are same length, lowercase. Example:
start="hit", end="cog", wordList=["hot","dot","dog","lot","log","cog"] → 5 (hit → hot → dot → dog →
cog). Return 0 if impossible.

In [ ]:
from collections import deque

start="hit"
end="cog"
wordList=["hot","dot","dog","lot","log","cog"]
wordSet=set(wordList)
queue=deque([(start,1)])
while queue:
  word,steps=queue.popleft()
  if word==end:
    print(steps)
    break
  for i in range(len(word)):
    for ch in 'abcdefghijklmnopqrstuvwxyz':
      next_word=word[:i]+ ch + word[i+1:]
      if next_word in wordSet:
        wordSet.remove(next_word)
        queue.append((next_word,steps+1))
else:
  print(0)
end="cog"
wordList=["hot","dot","dog","lot","log","cog"]
wordSet=set(wordList)
queue=deque([(start,1)])
while queue:
  word,steps=queue.popleft()
  if word==end:
    print(steps)
    break
  for i in range(len(word)):
    for ch in 'abcdefghijklmnopqrstuvwxyz':
      next_word=word[:i]+ ch + word[i+1:] # Corrected variable name 'c' to 'ch'
      if next_word in wordSet:
        wordSet.remove(next_word)
        queue.append((next_word,steps+1))
else:
  print(0)



5
5


#### **Assignment.4**

### 1. Create a dictionary of 5 students with their names as keys and marks as values. Print all
the keys and values.

In [ ]:
# Creating a dictionary of students with their marks
students = {
    "khusi": 85,
    "arsh": 92,
    "Amrit": 78,
    "gur": 88,
    "prabh": 95
}
print(students)


{'khusi': 85, 'arsh': 92, 'Amrit': 78, 'gur': 88, 'prabh': 95}


### 2. Write a program to count the frequency of each character in a given string using a
dictionary.


In [ ]:
x=input("enter the string=")
frequency={}
for i in x:
  if i in frequency:
    frequency[i]+=1
  else:
      frequency[i]=1
  print(frequency)

enter the string="hello world"
{'"': 1}
{'"': 1, 'h': 1}
{'"': 1, 'h': 1, 'e': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 2}
{'"': 1, 'h': 1, 'e': 1, 'l': 2, 'o': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 2, 'o': 1, ' ': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 2, 'o': 1, ' ': 1, 'w': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 2, 'o': 2, ' ': 1, 'w': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 2, 'o': 2, ' ': 1, 'w': 1, 'r': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1}
{'"': 1, 'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}
{'"': 2, 'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}


### 3. Create a dictionary with names as keys and ages as values. Print the name(s) of the oldest
person(s).



In [ ]:
dict_ages={"gur":21, "khushi":18.5,"jeet":37,"preet":40,"reet":16.5}
oldest_people=max(dict_ages.values())
print("oldest people is:")
for i,j in dict_ages.items():
 if j==oldest_people:
  print(i)


oldest people is:
preet


### 4. Merge two dictionaries and print the merged dictionary.

In [ ]:
dict1={'gur':21,'khushi':18.5,'jeet':37,'preet':40,'reet':16.5}
dict2={'s1':'s','k1':'k','s2':'s','s3':'s','j1':'j'}
print("dict1:",dict1)
print("dict2:",dict2)
dict1.update(dict2)
print("after merging:",dict1)

dict1: {'gur': 21, 'khushi': 18.5, 'jeet': 37, 'preet': 40, 'reet': 16.5}
dict2: {'s1': 's', 'k1': 'k', 's2': 's', 's3': 's', 'j1': 'j'}
after merging: {'gur': 21, 'khushi': 18.5, 'jeet': 37, 'preet': 40, 'reet': 16.5, 's1': 's', 'k1': 'k', 's2': 's', 's3': 's', 'j1': 'j'}


### 5. Create a dictionary where the keys are numbers between 1 and 10, and the values are
their squares

In [ ]:
dict={}
for i in range(1,11):
  dict[i]=i*i

print(dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


### 6. Write a program that inverts a dictionary (i.e., swaps keys and values). Assume all values
are unique.

In [ ]:
dict={'a':1,'b':2,'c':3,'d':4,'e':5}

dict_i={}

for key,value in dict.items():
  dict_i[value]=key

print("initial:",dict)
print("invrted:",dict_i)

initial: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
invrted: {1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e'}


### 7. Given a nested dictionary of students and their subject-wise marks, calculate and print
the average marks for each student.


In [ ]:
dict_students={'jeet':{'maths':85,'english':90,'science':85,'punjabi':96},
              'khushi':{'maths':99,'english':99,'science':98,'punjabi':98},
              'reet':{'maths':85,'english':95,'science':90,'punjabi':96},
              'deepu':{'maths':88,'english':92,'science':85,'punjabi':96}}

for name,marks in dict_students.items():
  total_marks=sum(marks.values())
  avg_marks=total_marks/len(marks)
  print(name,avg_marks)

for name,marks in dict_students.items():
  total_marks=sum(marks.values())
  avg_marks=total_marks/len(marks)
  print(name,avg_marks)


jeet 89.0
khushi 98.5
reet 91.5
deepu 90.25
jeet 89.0
khushi 98.5
reet 91.5
deepu 90.25


### 8. Write a program to group words by their length from a list using a dictionary.

In [ ]:
a=input("enter the word seperated by space(without comma): ")


word=a.split()
length={}
for i in word:
  l=len(i)
  if l in length:
    length[l].append(i)
  else:
    length[l]=[i]
print(length)



enter the word seperated by space(without comma): apple banana watermelon
{5: ['apple'], 6: ['banana'], 10: ['watermelon']}


### 10. Create a program that takes a list of tuples (name, score) and builds a dictionary
where each name is a key, and the value is a list of all their scores. Then calculate and print
each person's average score.

In [ ]:
people=[('sam',85),
        ('khushi',90), # Added missing comma
        ('sukh',98),   # Added missing comma
        ('sarb',92),   # Added missing comma
        ('jagg',88)]
# Removed the incorrect indentation from the line below
person_scores={}
for name,score in people:
  if name in person_scores: # Changed variable name from dict to person_scores
    person_scores[name].append(score) # Changed variable name from dict to person_scores
  else:
    person_scores[name]=[score] # Changed variable name from dict to person_scores

for name,scores_list in person_scores.items(): # Changed variable name from dict to person_scores and score to scores_list
    avg_score=sum(scores_list)/len(scores_list) # Changed variable name from score to scores_list
    print(name,avg_score)



sam 85.0
khushi 90.0
sukh 98.0
sarb 92.0
jagg 88.0


### **Assignment.5**

### 1.WAP to make a pyramid.

In [ ]:
people=[('jeet',85),
        ('khushi',90), # Added missing comma
        ('sukh',98),   # Added missing comma
        ('reet',92),   # Added missing comma
        ('preet',88)]
# Removed the incorrect indentation from the line below
person_scores={}
for name,score in people:
  if name in person_scores: # Changed variable name from dict to person_scores
    person_scores[name].append(score) # Changed variable name from dict to person_scores
  else:
    person_scores[name]=[score] # Changed variable name from dict to person_scores

for name,scores_list in person_scores.items(): # Changed variable name from dict to person_scores and score to scores_list
    avg_score=sum(scores_list)/len(scores_list) # Changed variable name from score to scores_list
    print(name,avg_score)



jeet 85.0
khushi 90.0
sukh 98.0
reet 92.0
preet 88.0


## **Assignment.5**

### 1.WAP to make a pyramid.

In [ ]:
def pyramid(n,current=1):
    if current > n :
        return
    spaces=' ' * (n-current)
    stars='*'*(2*current-1)
    print(spaces+stars)
    pyramid(n,current+1)
n=int(input("enter no.of lines:"))
pyramid(n)

enter no.of lines:5
    *
   ***
  *****
 *******
*********


### 2.WAP to generate a pattern like star.
### *
### **
### ***
### ****


In [ ]:
def pattern(n,current=1):
  if (current > n):
   return
  print('*'* current)
  pattern(n,current+1)
n=int(input("enter no.of lines:"))
print(pattern(n))

enter no.of lines:4
*
**
***
****
None


### 3.WAP to draw square pattern like star.

In [ ]:
def square_pattern(n):
  for i in range(n):
    print(" * " * n)

size=int(input("enter the size of square:"))
square_pattern(size)

enter the size of square:5
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 


### 4.WAP to draw a circular pattern like star.

In [ ]:
import math
radius=int(input("enter the radius of circle:"))
for i in range(-radius,radius+1):
  for j in range(-radius,radius+1):
    if abs(i**2+j**2-radius**2)<radius:
      print("*",end="")
    else:
      print(" ",end="")
  print()

enter the radius of circle:6
    *****    
  **     **  
 **       ** 
 *         * 
*           *
*           *
*           *
*           *
*           *
 *         * 
 **       ** 
  **     **  
    *****    


### 5.WAP to draw a rectangular pattern like star.

In [ ]:
rows=int(input("enter the number of rows:"))
colms=int(input("enter the number of colms:"))
for i in range(rows):
  print("*"*colms)

enter the number of rows:5
enter the number of colms:7
*******
*******
*******
*******
*******


### **Assignment.6**

### 1.write a program to create a tuple with different data types and print its type.

In [ ]:
data=('hello world',13,1.3,True)
print(data)
print(type(data))

('hello world', 13, 1.3, True)
<class 'tuple'>


### 2.Given a tuple t=(10,20,30,40,50),write a program to access the second last element.

In [ ]:
t=(10,20,30,40,50)
second_last_element=t[-2]
print("second last element of given tuple is:",second_last_element)

second last element of given tuple is: 40


### 3.. Write a program to count the number of times a given element appears in a tuple.

In [ ]:
tuple=(1,2,5,6,5,3,5,8,4,1,9,1,2,0,6,3,4,14)
t=tuple.count(5)
print(t)

3


###  4. Write a program to convert a tuple of strings into a single string. Example: ('Python', 'is', 'fun') -->
 'Python is fun'

In [ ]:
tuple_of_strings=('python','is','fun')
single_string=' '.join(tuple_of_strings)
print(single_string)

python is fun


###  5. Write a Python program to find the index of an element in a tuple.

In [ ]:
my_tuple=(1,2,3,4,5,6,7,8,9,10)
t=my_tuple.index(4)
print(t)

3


###  Set Questions:
 6. Write a Python program to create two sets and perform union, intersection, and difference
 operations.

In [ ]:
set1={10,20,30,40,50}
set2={10,40,30,55,80}
union=set1.union(set2)
print("union:",union)
intersection=set1.intersection(set2)
print("intersection:",intersection)
difference=set1.difference(set2)
print("difference:",difference)

union: {40, 10, 80, 50, 20, 55, 30}
intersection: {40, 10, 30}
difference: {50, 20}


###  7. Write a program to check if a given element is present in a set or not.

In [ ]:
set1={10,20,30,40,50}
element=int(input("enter the element"))
if element in set1:
  print("element is present in set1")
else:
  print("element is not present in set1")

enter the element66
element is not present in set1


###  8. Write a program to remove duplicate elements from a list using a set.

In [ ]:
my_list=[10,20,40,80,10,20,30,50,60]
unique=list(set(my_list))
print(unique)

[40, 10, 80, 50, 20, 60, 30]


###  9. Write a Python program to find the symmetric difference between two sets.


In [ ]:
set1={'blue','black','green','grey'}
set2={'orange','grey','black','pink'}
symmetric_difference=set1.symmetric_difference(set2)
print(symmetric_difference)

{'green', 'pink', 'orange', 'blue'}


###  10. Given a list of numbers, write a Python program to find all unique elements using sets.

In [ ]:
list=[2,9,8,4,5,6,8,9,10,4,1,2,3,4,5,6,7,8,9,10]
unique=set(list)
print("unique elements:",unique)

unique elements: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


### **Assignment.7**

###  1. Write a function to find the factorial of a number using recursion.

In [ ]:
def factorial(n):
  if n<0:
      return "facorial is not defined for negative numbers"
  elif n==0 or n==1:
      return 1
  else:
      result=1
      for i in range(2,n+1):
          result*=i
      return result
n=int(input("enter the number:"))
print(factorial(n))


enter the number:6
720


###  2. Write a function that checks whether a number is prime or not.

In [ ]:
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(n**0.5+1)):
        if n%i==0:
            return False
    return True
n=int(input("enter the number:"))
print(is_prime(n))

enter the number:10
False


###  3. Create a function that takes a string as input and returns the number of vowels in it.

In [ ]:
def count_vowels(s):
  vowels='aeiouAEIOU'
  count=0
  for char in s:
    if char in vowels:
      count+=1
  return count
x=input("enter the string:")
print(count_vowels(x))

enter the string:hello world
3


###  4. Write a function that accepts a list of numbers and returns the maximum and minimum values.

In [ ]:
def max_min(number):
  h=max(number)
  l=min(number)
  return h,l
s=list(map(int,input("enter the number:").split(',')))
h,l=max_min(s)
print("maximum value is:",h)
print("minimum value is:",l)


enter the number:1,2,3,5,10,41,15,26,0
maximum value is: 41
minimum value is: 0


###  5. Write a Python function to calculate the nth Fibonacci number using recursion.


In [ ]:
def fibonacci(f):
  if f<=0:
    return "enter the positive number"
  elif f==1:
    return 0
  elif f==2:
    return 1
  else: # Indent the rest of the code to be part of the else block
    a,b=0,1
    for _ in range (3, f): # Changed range upper limit to f as range is exclusive
      a,b=b,a+b
    return b
x=int(input("enter the number:"))
print(fibonacci(x))

enter the number:13
89


###  6. Create a function that accepts two numbers and returns their greatest common divisor (GCD).

In [ ]:
def number(a,b):
  while b !=0:
    a,b=b,a%b
  return a


###  7. Write a function that takes a list and returns a new list with only unique elements.

In [ ]:
def unique_elements(my_list):
  return list(set(my_list))
list1 = list(input("enter a list seperated by a comma(,):").split(','))
print(f"unique elements are:{unique_elements(list1)}")



enter a list seperated by a comma(,):1,22,32,4,56,24
unique elements are:['22', '4', '24', '1', '32', '56']


###  8. Write a function to count the frequency of each word in a given string.

In [ ]:
def word_frequency(string):
    words = string.split()
    frequency = {}
    for word in words:
        word = word.lower()
        frequency[word] = frequency.get(word,0)+1
    return frequency
x = input("enter the string seperated by a space:")
print(word_frequency(x))

enter the string seperated by a space:hi i am gurpreet
{'hi': 1, 'i': 1, 'am': 1, 'gurpreet': 1}


###  9. Write a function that takes a number and returns True if it is a palindrome, otherwise False.

In [ ]:
def is_palindrome(number):
  return str(number)==str(number)[::-1]
num=int(input("enter the number:"))
print(is_palindrome(num))


def is_palindrome(num):
  s=str(num)
  return s==s[::-1]
  number=int(input("enter the number:"))
  print(is_palindrome(number))

enter the number:130
False


###  10. Create a function that takes a temperature in Celsius and returns it in Fahrenheit.

In [ ]:
def celsius_to_fahrenheit(celsius):
    return ((celsius*9/5)+32)
temp=int(input("enter the temperature:"))
print("fahrenheit is:",celsius_to_fahrenheit(temp))

enter the temperature:38
fahrenheit is: 100.4


## **Assignment.8**

###  1. Write a Python program to create a new text file and write the text 'Hello, File Handling!' to it.

In [66]:
with open("python.txt",'w') as py:
  py.write("Hello,File Handling")


## 2. Write a Python program to read the contents of 'example.txt' and display them on the screen.

In [68]:
with open("python.txt", "r") as ex:
  print("Example: ", ex.read())

Example:  Hello,File Handling


## 3. Write a Python program to count the number of words in a given text file.

In [69]:
def py(num):
  with open(num, "r") as c:
    text = c.read()
    words = text.split()
    print("number of words in a file:",len(words))
py("python.txt")

number of words in a file: 2


## 4. Write a Python program to read a file and print only those lines which start with the letter 'A'.

In [70]:
def l(lines):
  with open(lines, "r") as fs:
    for line in fs:
      if line.strip().startswith("A"):
        print(line.strip())
l("python.txt")

## 5. Write a Python program to merge the contents of two files into a third file.

In [71]:
with open("filehandling.txt", "w") as fh:
  fh.write("This is the first file.\n")
  fh.write("It contains some text for merging.")

## **Assignment.9**

###  1. Create a NumPy array with values from 1 to 10. Print the shape, dimension, and data type of the
 array.

In [61]:
import numpy as np
array=np.arange(1,11)
print(array)
print("shape:",array.shape)
print("dimension:",array.ndim)
print("data type:",array.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)
dimension: 1
data type: int64


###  2. Create a 3x3 NumPy array of all zeros and another of all ones. Then create a 3x3 identity matrix.

In [60]:
arr_zero = np.zeros((3,3))
print("3*3 matrix of zeros:")
print(arr_zero)

arr_one = np.ones((3,3))
print("\n3*3 matrix of ones:")
print(arr_one)

arr_identity = np.identity(3)
print("\n3*3 identity matrix:")
print(arr_identity)

3*3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3*3 matrix of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3*3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###  3. Generate an array of 15 random integers between 10 and 100 using np.random.randint. Reshape
 it into a 3x5 matrix and print it.

In [59]:
arr = np.random.randint(10,100,15)
print(f"15 random integers between 10 and 100:")
print("\nreshaped to 3*5 matrix:")
print(arr.reshape(3,5))

15 random integers between 10 and 100:

reshaped to 3*5 matrix:
[[71 96 85 72 33]
 [90 95 54 32 19]
 [36 68 40 54 40]]


###  4. Create a NumPy array from 1 to 20. Extract every 3rd element starting from index 1 using slicing.

In [58]:
arr = np.arange(1,21)
print("array from 1 to 20:")
print(arr)
print("\nevery 3rd element starting from index 1:")
print(arr[1::3])

array from 1 to 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

every 3rd element starting from index 1:
[ 2  5  8 11 14 17 20]


###  5. Create two arrays: a = np.array([2, 4, 6, 8]) and b = np.array([1, 3, 5, 7]). Perform element-wise
 ### addition, multiplication, and compare which elements in a are greater than in b.

In [57]:
x = np.array([2,4,6,8])
y = np.array([1,3,5,7])
print(f"addition:{x+y}")
print(f"multiplication:{x*y}")
print(f"comparison:{x>y}")

addition:[ 3  7 11 15]
multiplication:[ 2 12 30 56]
comparison:[ True  True  True  True]


###  6. Create a NumPy array with 20 random values (0 to 1) using np.random.rand(). Find the mean,
 median, standard deviation, min, and max.

In [56]:
a = np.random.rand(20)
print(f"array with 20 random values:,{a}\n")
print(f"mean:{np.mean(a)}")
print(f"median:{np.median(a)}")
print(f"standard deviation:{np.std(a)}")
print(f"min:{np.min(a)}")

array with 20 random values:,[0.92443276 0.09513564 0.29924375 0.13008974 0.0335428  0.32464309
 0.49067873 0.61644804 0.31541603 0.6668478  0.38958965 0.12174757
 0.26186801 0.8757024  0.02905904 0.62361036 0.04904992 0.11076624
 0.87149838 0.3505039 ]

mean:0.3789936920734288
median:0.32002955933506233
standard deviation:0.28789248951663277
min:0.029059035323252602


### 7. Given: arr = np.array([[3, 5], [7, 9]]). Find the sum across rows and columns using axis.

In [55]:
arr = np.array([[3,5],[7,9]])
print(f"sum across rows:{np.sum(arr,axis=1)}")
print(f"sum across columns:{np.sum(arr,axis=0)}")

sum across rows:[ 8 16]
sum across columns:[10 14]


###  8. Create a NumPy array of numbers from 10 to 30. Filter and print only the even numbers using
 boolean indexing.

In [54]:
arr = np.arange(10,31)
print(f"array of numbers from 10 to 30:{arr}")
print(f"even numbers:{arr[arr%2==0]}")

array of numbers from 10 to 30:[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
even numbers:[10 12 14 16 18 20 22 24 26 28 30]


###  9. Generate an array of 10 random integers from 1 to 100. Replace all elements greater than 50 with-1.

In [53]:
arr = np.random.randint(1,101,10)
print(f"array of 10 random integers from 1 to 100:{arr}")
arr[arr>50]=-1
print(f"replacing all elements greater than 50 with -1:{arr}")

array of 10 random integers from 1 to 100:[31  1 64 98  1 97 67 30 71 61]
replacing all elements greater than 50 with -1:[31  1 -1 -1  1 -1 -1 30 -1 -1]


###  10. Create two arrays: x = np.array([[1, 2], [3, 4]]) and y = np.array([[5, 6], [7, 8]]). Stack them
 vertically and horizontally, then flatten the result into a 1D array.

In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v_arr = np.vstack((x,y))
print(f"vertically stacked array:{v_arr}")

h_arr = np.hstack((x,y))
print(f"horizontally stacked array:{h_arr}")

fv_arr = v_arr.flatten()
print(f"flattened vertically stacked array:{fv_arr}")

fh_arr = h_arr.flatten()
print(f"flattened horizontally stacked array:{fh_arr}")


vertically stacked array:[[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontally stacked array:[[1 2 5 6]
 [3 4 7 8]]
flattened vertically stacked array:[1 2 3 4 5 6 7 8]
flattened horizontally stacked array:[1 2 5 6 3 4 7 8]


### **Assignment.10**

### 1. Load the dataset and display the first 10 rows.

In [ ]:
import pandas as pd
import numpy as np

In [51]:
from google.colab import drive

drive.mount('/content/drive')
df =pd.read_csv('/diamonds.csv')
df.head(10)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0           1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1           2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2           3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3           4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4           5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
5           6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94   
6           7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95   
7           8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07   
8           9   0.22       Fair     E     VS2   65.1   61.0    337  3.87   
9          10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00   

      y     z  
0  3.98  2.43  
1  3.84  2.31  
2  4.07  2.31  
3  4.23  2.63  
4  4.35  2.75  
5  3.96  2.48  
6  3.98  2.47  
7  4.11  2.53  
8  3.78  2.49  
9  4.05  2.39

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


###  2. Check the shape and column names of the dataset.

In [49]:
df.shape

(53940, 11)

In [48]:
df.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='object')

###  3. Find and fill missing numeric values with their respective column means.

In [47]:
df.loc[[3,7],"price"]= np.nan
df




Unnamed: 0  carat        cut color clarity  depth  table   price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0   326.0  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0   326.0  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0   327.0  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0     NaN  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0   335.0  4.34   
...           ...    ...        ...   ...     ...    ...    ...     ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0  2757.0  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0  2757.0  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0  2757.0  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0  2757.0  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0  2757.0  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [46]:
df["price"]=df["price"].fillna(df["price"].mean())
df.head(8)

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0           1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1           2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2           3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3           4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4           5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
5           6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94   
6           7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95   
7           8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07   

      y     z  
0  3.98  2.43  
1  3.84  2.31  
2  4.07  2.31  
3  4.23  2.63  
4  4.35  2.75  
5  3.96  2.48  
6  3.98  2.47  
7  4.11  2.53

###  4. Filter rows where `cut` is "Ideal" and `color` is "E".

In [45]:
filter_df = df[(df['cut'] == 'Ideal') & (df['color'] == 'E')]
filter_df

Unnamed: 0  carat    cut color clarity  depth  table  price     x  \
0               1   0.23  Ideal     E     SI2   61.5   55.0    326  3.95   
82             83   0.26  Ideal     E    VVS2   62.9   58.0    554  4.02   
90             91   0.70  Ideal     E     SI1   62.5   57.0   2757  5.70   
109           110   0.59  Ideal     E    VVS2   62.0   55.0   2761  5.38   
111           112   0.74  Ideal     E     SI2   62.2   56.0   2761  5.80   
...           ...    ...    ...   ...     ...    ...    ...    ...   ...   
53876       53877   0.70  Ideal     E     SI1   61.7   55.0   2745  5.71   
53878       53879   0.51  Ideal     E    VVS1   61.9   54.0   2745  5.17   
53891       53892   0.56  Ideal     E    VVS1   62.1   56.0   2750  5.28   
53915       53916   0.77  Ideal     E     SI2   62.1   56.0   2753  5.84   
53926       53927   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71   

          y     z  
0      3.98  2.43  
82     4.06  2.54  
90     5.72  3.57  
109    5.43  3.35  
111    5.84  3.62  
...     ...   ...  
53876  5.74  3.53  
53878  5.11  3.18  
53891  5.29  3.28  
53915  5.86  3.63  
53926  5.73  3.54  

[3903 rows x 11 columns]

###  5. Group by `cut` and compute the average `price` for each group.

In [44]:
df.groupby(['cut'])['price'].mean()


cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

###  6. Sort the data by `carat` in descending order and show the top 5 rows.

In [43]:
df.sort_values(by='carat',ascending=False).head(5)


Unnamed: 0  carat      cut color clarity  depth  table  price      x  \
27415       27416   5.01     Fair     J      I1   65.5   59.0  18018  10.74   
27630       27631   4.50     Fair     J      I1   65.8   58.0  18531  10.23   
27130       27131   4.13     Fair     H      I1   64.8   61.0  17329  10.00   
25999       26000   4.01  Premium     J      I1   62.5   62.0  15223  10.02   
25998       25999   4.01  Premium     I      I1   61.0   61.0  15223  10.14   

           y     z  
27415  10.54  6.98  
27630  10.16  6.72  
27130   9.85  6.43  
25999   9.94  6.24  
25998  10.10  6.17

###  7. Convert the `price` column to a NumPy array and find its mean, median, and standard deviation.

In [42]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
df =pd.read_csv('/diamonds.csv')
price_array = df['price'].to_numpy()
print('mean',np.mean(price_array))
print('median',np.median(price_array))
print('standard deviation',np.std(price_array))



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
mean 3932.799721913237
median 2401.0
standard deviation 3989.4027576288736


###  8. Count diamonds with `price > 5000` and `carat > 1` using NumPy conditions.


In [41]:
df[(df['price']>5000) & ( df['carat']>1)]

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
11416       11417   1.16      Ideal     E     SI2   62.7   56.0   5001  6.69   
11417       11418   1.16      Ideal     E     SI2   59.9   57.0   5001  6.80   
11421       11422   1.07      Ideal     I     SI1   61.7   56.1   5002  6.57   
11422       11423   1.10      Ideal     H     SI2   62.0   56.5   5002  6.58   
11423       11424   1.20      Ideal     J     SI1   62.1   55.0   5002  6.81   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
27745       27746   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95   
27746       27747   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20   
27747       27748   1.51      Ideal     G      IF   61.7   55.0  18806  7.37   
27748       27749   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90   
27749       27750   2.29    Premium     I     VS2   60.8   60.0  18823  8.50   

          y     z  price_updated  
11416  6.73  4.21         4500.9  
11417  6.82  4.08         4500.9  
11421  6.59  4.06         4501.8  
11422  6.63  4.09         4501.8  
11423  6.84  4.24         4501.8  
...     ...   ...            ...  
27745  8.00  5.01        16922.7  
27746  8.13  5.11        16923.6  
27747  7.41  4.56        16925.4  
27748  7.97  5.04        16936.2  
27749  8.47  5.16        16940.7  

[13736 rows x 12 columns]

###  9. Create a new column `price_updated` by increasing `price` by 10% using NumPy.

In [40]:
df = pd.read_csv('/diamonds.csv')
df['price_updated'] = df['price'] - (df['price'] * 0.1)
df

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  price_updated  
0      3.98  2.43          293.4  
1      3.84  2.31          293.4  
2      4.07  2.31          294.3  
3      4.23  2.63          300.6  
4      4.35  2.75          301.5  
...     ...   ...            ...  
53935  5.76  3.50         2481.3  
53936  5.75  3.61         2481.3  
53937  5.68  3.56         2481.3  
53938  6.12  3.74         2481.3  
53939  5.87  3.64         2481.3  

[53940 rows x 12 columns]

###  10. Create a `volume` column as `x*y*z` and find the average `price` where `volume > 50`.

In [39]:
df = pd.read_csv('/diamonds.csv')
df['volume'] = df['x'] * df['y'] * df['z']
avg_price = df[df['volume'] > 50]['price'].mean()
print(df.head())
print(f"average price:{avg_price}")
df

   Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z     volume  
0  2.43  38.202030  
1  2.31  34.505856  
2  2.31  38.076885  
3  2.63  46.724580  
4  2.75  51.917250  
average price:4183.0099982039155


Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z      volume  
0      3.98  2.43   38.202030  
1      3.84  2.31   34.505856  
2      4.07  2.31   38.076885  
3      4.23  2.63   46.724580  
4      4.35  2.75   51.917250  
...     ...   ...         ...  
53935  5.76  3.50  115.920000  
53936  5.75  3.61  118.110175  
53937  5.68  3.56  114.449728  
53938  6.12  3.74  140.766120  
53939  5.87  3.64  124.568444  

[53940 rows x 12 columns]

## **Assignment.11**

### 1. Calculate the number of days with missing temperature data (Max, Min, or Mean).

In [75]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/diamonds.csv')
df

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [77]:
df.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [87]:
df.iloc[:,1] = np.nan
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1    NaN    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2    NaN  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3    NaN     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4    NaN  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5    NaN     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [88]:
df['Temperature'].fillna(df['Temperature'].max(),inplace = True)
df.head()

KeyError: 'Temperature'

## **ASSIGNMENT 14**

## basic file obsevasion.

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score



iris = pd.read_csv("/Iris (1).csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [90]:
iris.describe()
iris.info()
iris.columns
iris.dtypes
iris['Species'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [33]:
iris.shape

(150, 6)

In [34]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [35]:
model = LogisticRegression()
X_train = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y_train = iris['Species']
model.fit(X_train, y_train)

LogisticRegression()

In [72]:
X = pd.DataFrame([[6,3.0,2,5],[6,8,2,4]], columns=X_train.columns)
result = model.predict(X)
print("prediction is :",result)

prediction is : ['Iris-virginica' 'Iris-setosa']
